
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ikbar
 */
public class Admin extends javax.swing.JFrame{

     String[] currencyUnits = {
        "Units",
        "Australian Dollar",
        "British Pound Sterling",
        "European Euro",
        "Indonesian Rupiah",
        "Singapore Dollar",
        "US Dollar"
    };
     
    
    
    double US_Dollar = 1.31;
    double Indonesian_Rupiah = 18850.31;
    
    
    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbAdmCountry1 = new javax.swing.JComboBox<>();
        cbAdmCountry2 = new javax.swing.JComboBox<>();
        tfAdmVal1 = new javax.swing.JTextField();
        tfCountryCurr2 = new javax.swing.JTextField();
        tfAdmVal2 = new javax.swing.JTextField();
        lblAdmCurr2 = new javax.swing.JLabel();
        lblAdmCurr1 = new javax.swing.JLabel();
        btnAdmConvert = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CURRENCY CONVERTER");

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("From");

        jLabel3.setText("To");

        cbAdmCountry1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Country", "Australia", "British", "Europe", "Indonesia", "Singapore", "USA" }));
        cbAdmCountry1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAdmCountry1ItemStateChanged(evt);
            }
        });
        cbAdmCountry1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAdmCountry1ActionPerformed(evt);
            }
        });

        cbAdmCountry2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Country", "Australia", "British", "Europe", "Indonesia", "Singapore", "USA" }));
        cbAdmCountry2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAdmCountry2ItemStateChanged(evt);
            }
        });

        tfCountryCurr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCountryCurr2ActionPerformed(evt);
            }
        });

        lblAdmCurr2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAdmCurr2.setText("Units");

        lblAdmCurr1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAdmCurr1.setText("Units");

        btnAdmConvert.setText("Convert");
        btnAdmConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmConvertActionPerformed(evt);
            }
        });

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(37, 37, 37)
                        .addComponent(btnAdmConvert)
                        .addGap(227, 227, 227)
                        .addComponent(jButton1)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAdmCountry1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfAdmVal1)
                    .addComponent(lblAdmCurr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAdmCurr2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAdmCountry2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfCountryCurr2)
                    .addComponent(tfAdmVal2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cbAdmCountry1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(tfAdmVal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAdmCurr1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cbAdmCountry2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfCountryCurr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(tfAdmVal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAdmCurr2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdmConvert)
                            .addComponent(jButton3))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Login login = new Login();
       login.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfCountryCurr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCountryCurr2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCountryCurr2ActionPerformed

    private void cbAdmCountry1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAdmCountry1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAdmCountry1ActionPerformed

    private void cbAdmCountry1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAdmCountry1ItemStateChanged
        int position = cbAdmCountry1.getSelectedIndex();
        
        lblAdmCurr1.setText(currencyUnits[position]);

    }//GEN-LAST:event_cbAdmCountry1ItemStateChanged

    private void cbAdmCountry2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAdmCountry2ItemStateChanged
         int position = cbAdmCountry2.getSelectedIndex();
        
        lblAdmCurr2.setText(currencyUnits[position]);

    }//GEN-LAST:event_cbAdmCountry2ItemStateChanged

    private void btnAdmConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmConvertActionPerformed

        if(cbAdmCountry2.getSelectedIndex()== 0 || cbAdmCountry1.getSelectedIndex()== 0){
        JOptionPane.showMessageDialog(null,"Please Select Country", "Error", JOptionPane.ERROR_MESSAGE);
            
        }else if (cbAdmCountry2.getSelectedIndex() == cbAdmCountry1.getSelectedIndex()){
            JOptionPane.showMessageDialog(null,"Cannot Convert Same Currency", "Error", JOptionPane.ERROR_MESSAGE);
        
        }else if(tfAdmVal1.getText().equals("") || tfCountryCurr2.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Please Enter Value", "Error", JOptionPane.ERROR_MESSAGE);
       }else{
        double Val1 = Double.parseDouble(tfAdmVal1.getText());
        double Val2 = Double.parseDouble(tfCountryCurr2.getText());
        
        String result = Double.toString(Val1 * Val2);

        tfAdmVal2.setText(result);
        }
        
        
       
        
        /*
        double valueConvert = Double.parseDouble(tfAdmVal1.getText());
        
        double toPounds = 0.0;
        
        double valueConverted = 0.0;
        
        switch(cbAdmCountry1.getSelectedItem().toString()){
            case "USA": toPounds = valueConvert / US_Dollar;
            break;
            
            case "Indonesia": toPounds = valueConvert / Indonesian_Rupiah;
            break;
            
            default: toPounds = 0.0;
    }                                        
   
        
        switch(cbAdmCountry2.getSelectedItem().toString()){
            case "USA": valueConverted = toPounds * US_Dollar;
            break;
            
            case "Indonesia": valueConverted = toPounds * Indonesian_Rupiah;
            break;
            
            default: valueConverted = toPounds * 0.0;
   
        }
        
        String value = String.format("%.2f",valueConverted);
        
        tfAdmVal2.setText(value);*/
    }//GEN-LAST:event_btnAdmConvertActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cbAdmCountry1.setSelectedIndex(0);
        cbAdmCountry2.setSelectedIndex(0);
        tfAdmVal1.setText(null);
        tfAdmVal2 .setText(null);
        tfCountryCurr2.setText(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmConvert;
    private javax.swing.JComboBox<String> cbAdmCountry1;
    private javax.swing.JComboBox<String> cbAdmCountry2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAdmCurr1;
    private javax.swing.JLabel lblAdmCurr2;
    private javax.swing.JTextField tfAdmVal1;
    private javax.swing.JTextField tfAdmVal2;
    private javax.swing.JTextField tfCountryCurr2;
    // End of variables declaration//GEN-END:variables
    
}


